* debian/patches/002_md5_deprecation.dpatch:   Use hashlib instead of deprecated md5 functions. Thanks to Michael Bienia   from Ubuntu (Closes: #517993) * debian/control:   - No longer Provides ${python:Provides}   - Update Homepage - upstream moved (in watch too)   - Set XS-Python-Version: >= 2.5 (as required by the hashlib patch) * debian/rules:   - Run setup.py with current python version only.   - Respect nocheck in DEB_BULID_OPTIONS (although failed tests don't abort     build, as several tests fail) * Bump standards version to 3.8.4 (no additional changes needed).
git-svn-id: svn://svn.debian.org/python-modules/packages/urlgrabber/trunk@13520 771dd761-d7fa-0310-a302-f036d1c1ebb6

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -9,8 +9,6 @@
 # Uncomment this to turn on verbose mode.
 #export DH_VERBOSE=1
 
-PYVERS = $(shell pyversions -r)
-
 configure: configure-stamp
 configure-stamp:
 	dh_testdir
@@ -20,10 +18,13 @@ build: patch build-stamp
 
 build-stamp: configure-stamp
 	dh_testdir
-	for py in $(PYVERS); do \
-		$$py setup.py build; \
+	python setup.py build
+ifeq (,$(findstring nocheck,$(DEB_BUILD_OPTIONS)))
+	# we should set -e, but all the tests fail.
+	for py in $(shell pyversions -r); do \
 		$$py test/runtests.py; \
 	done
+endif
 	touch build-stamp
 
 clean: clean-patched unpatch
@@ -32,9 +33,6 @@ clean-patched:
 	dh_testdir
 	dh_testroot
 	-rm -f build-stamp configure-stamp
-	for py in $(PYVERS); do \
-		$$py setup.py clean; \
-	done
 	python setup.py clean
 	find $(CURDIR) -name "*.pyc" -exec rm -f '{}' \;
 	dh_clean
@@ -54,9 +52,7 @@ install: build
 	dh_clean -k
 	dh_installdirs
 	# Add here commands to install the package into debian/urlgrabber.
-	for py in $(PYVERS); do \
-		$$py setup.py install --prefix=/usr --root=$(CURDIR)/debian/python-urlgrabber; \
-	done
+	python setup.py install --prefix=/usr --root=$(CURDIR)/debian/python-urlgrabber
 	# remove unneeded documents installed by setup.py
 	-rm -rf $(CURDIR)/debian/python-urlgrabber/usr/share/doc/urlgrabber-3*
 
